version: '3.8'

services:
  purpur:
    image: itzg/minecraft-server:java11
    container_name: purpur-build
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "1.16.5"
      MEMORY: "6G"
      SERVER_PORT: "25565"
      OVERRIDE_ICON: true
      ENABLE_RCON: true
      ONLINE_MODE: true
      ALLOW_NETHER: false
      ENABLE_COMMAND_BLOCK: true
      MOTD: "OneServer | Red Build Server"
      MODE: "creative"
      DIFFICULTY: "peaceful"
      MAX_PLAYERS: 50
      SPAWN_PROTECTION: 1
      TZ: "Asia/Tokyo"
      OP_PERMISSION_LEVEL: 3
      OPS: "M1n1don"
      ENABLE_WHITELIST: true
      WHITELIST: "M1n1don,Junpei0,Ayadu,Reita1127,Haruchl_,iorii"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - "../build:/data"
