version: '3.8'

services:
  purpur:
    image: itzg/minecraft-server:java11
    container_name: purpur-event1
    ports:
      - "25510:25510"
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "1.16.5"
      MEMORY: "6G"
      SERVER_PORT: "25510"
      OVERRIDE_ICON: true
      ENABLE_RCON: true
      ONLINE_MODE: true
      ALLOW_NETHER: false
      ENABLE_COMMAND_BLOCK: true
      MOTD: "OneServer | Red Event Server 1"
      MODE: "creative"
      DIFFICULTY: "peaceful"
      MAX_PLAYERS: 50
      SPAWN_PROTECTION: 1
      TZ: "Asia/Tokyo"
      OP_PERMISSION_LEVEL: 3
      OPS: "M1n1don"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - "../event1:/data"